theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

title: My GitHub Pages Site
description: This is my personal website.
author: John Doe
timezone: America/Los_Angeles

posts:
  - layout: default
    title: My First Post
    description: This is my first post.
  - layout: default
    title: My Second Post
    description: This is my second post.
